apiVersion: v1
appVersion: "1.16.1"
description: A Helm chart to install bitwarden_rs
name: bitwarden
version: 0.3.0
home: https://github.com/r-bar/helm-bitwarden_rs
maintainers:
  - name: Ryan Barth
    email: ryan@barth.tech
