---
resources:
  - name: cors-container-chart
    icon: ship-wheel
    type: helm-chart
    source:
      chart: cors-container
      repository_url: https://registry.barth.tech/chartrepo/library
      username: ((registry.username))
      password: ((registry.password))

jobs:
  - name: cors-container
    plan:
      - get: git-repo
        passed: [update-pipeline]
        trigger: true
      - put: build-status
        params:
          state: pending
          commit: git-repo
      - do:
          - task: test-cors-container
            file: git-repo/ci/helm-test-task.yaml
            input_mapping: {repository: git-repo}
            vars:
              chart-path: cors-container
              namespace: ((k8s-cluster.namespace))
              token: ((k8s-cluster.token))
              certificate-authority-data: ((k8s-cluster.certificate-authority-data))
              cluster-url: ((k8s-cluster.url))
          - put: cors-container-chart
            params:
              repository: git-repo/cors-container
        on_failure: &on_failure
          put: build-status
          params:
            state: failure
            commit: git-repo
        on_error: *on_failure
        on_abort: *on_failure
      - put: build-status
        params:
          state: success
          commit: git-repo
