---
resources:
  - name: repository
    type: git
    source:
      uri: https://github.com/r-bar/helm-charts.git
    webhook_token: push
    check_every: 24h

jobs:
  - name: bitwarden
    plan:
      - get: repository
        trigger: true
      - task: test-bitwarden
        file: repository/ci/helm-test-task.yaml
        #input_mapping: {repository: repository}
        vars:
          chart-path: repository/bitwarden
          namespace: ((k8s-token.namespace))
          token: ((k8s-token.token))
          certificate_authority_data: (("k8s-token"."ca.crt"))
          #certificate_authority_data: ""
  - name: mumble
    plan:
      - get: repository
        trigger: true
      - task: test-mumble
        file: repository/ci/helm-test-task.yaml
        #input_mapping: {repository: repository}
        vars:
          chart-path: repository/mumble
          namespace: ((k8s-token.namespace))
          token: ((k8s-token.token))
          #certificate_authority_data: ((k8s-token."ca.crt"))
          certificate_authority_data: ""
