---
resources:
  - name: repository
    type: git
    source:
      uri: https://github.com/r-bar/helm-charts.git
    webhook_token: push
    check_every: 24h

jobs:
  - name: bitwarden
    plan:
      - get: repository
        trigger: true
      - task: test-bitwarden
        file: repository/ci/helm-test-task.yaml
        vars:
          chart-path: repository/bitwarden
          namespace: ((k8s-cluster.namespace))
          token: ((k8s-cluster.token))
          certificate-authority-data: ((k8s-cluster.certificate-authority-data))
          cluster-url: ((k8s-cluster.url))
          #certificate_authority_data: ""
  - name: mumble
    plan:
      - get: repository
        trigger: true
      - task: test-mumble
        file: repository/ci/helm-test-task.yaml
        vars:
          chart-path: repository/mumble
          namespace: ((k8s-cluster.namespace))
          token: ((k8s-cluster.token))
          certificate-authority-data: ((k8s-cluster.certificate-authority-data))
          cluster-url: ((k8s-cluster.url))
