---
resource_types:
  - name: github-status
    type: docker-image
    source:
      repository: registry.barth.tech/library/concourse_github_status
      tag: latest


resources:

  - name: repository
    type: git
    source:
      uri: https://github.com/r-bar/helm-charts.git
    webhook_token: push
    check_every: 24h

  - name: build-status
    type: github-status
    source:
      owner: r-bar
      repository: helm-charts
      access_token: ((github-access-token))


jobs:
  - name: update-pipeline
    plan:
      - get: repository
        trigger: true

      - set_pipeline: helm-charts-ci
        file: repository/ci/pipeline.yaml

  - name: bitwarden
    plan:
      - get: repository
        passed: [update-pipeline]
        trigger: true
      - put: build-status
        params:
          state: pending
          commit: repository
      - do:
          - task: test-bitwarden
            file: repository/ci/helm-test-task.yaml
            vars:
              chart-path: repository/bitwarden
              namespace: ((k8s-cluster.namespace))
              token: ((k8s-cluster.token))
              certificate-authority-data: ((k8s-cluster.certificate-authority-data))
              cluster-url: ((k8s-cluster.url))
        on_failure:
          put: build-status
          params:
            state: failure
            commit: repository
        on_error:
          put: build-status
          params:
            state: error
            commit: repository
        on_abort:
          put: build-status
          params:
            state: error
            commit: repository
      - put: build-status
        params:
          state: success
          commit: repository

  - name: mumble
    plan:
      - get: repository
        passed: [update-pipeline]
        trigger: true
      - put: build-status
        params:
          state: pending
          commit: repository
      - do:
          - task: test-mumble
            file: repository/ci/helm-test-task.yaml
            vars:
              chart-path: repository/mumble
              namespace: ((k8s-cluster.namespace))
              token: ((k8s-cluster.token))
              certificate-authority-data: ((k8s-cluster.certificate-authority-data))
              cluster-url: ((k8s-cluster.url))
        on_failure:
          put: build-status
          params:
            state: failure
            commit: repository
        on_error:
          put: build-status
          params:
            state: error
            commit: repository
        on_abort:
          put: build-status
          params:
            state: error
            commit: repository
      - put: build-status
        params:
          state: success
          commit: repository
