---
resource_types:
  - name: github-status
    type: docker-image
    source:
      repository: registry.barth.tech/library/concourse_github_status
      tag: latest

  - name: helm-chart
    type: registry-image
    source:
      repository: jghiloni/helm-chart-resource
      tag: v0.1.1


resources:

  - name: git-repo
    icon: github
    type: git
    source:
      uri: git@github.com:r-bar/helm-charts.git
      branch: master
      private_key: ((git-config.ssh-private-key))
    webhook_token: ((webhook-token))
    check_every: 24h

  - name: build-status
    type: github-status
    icon: list-status
    source:
      owner: r-bar
      repository: helm-charts
      access_token: ((github-access-token))


#groups:
#  - name: setup
#    jobs: [update-pipeline]
#  - name: bitwarden
#    jobs: [bitwarden, bitwarden-release]
#  - name: mumble
#    jobs: [mumble]


jobs:
  - name: update-pipeline
    plan:
      - get: git-repo
        trigger: true

      - task: generate-full-pipeline
        config:
          platform: linux
          image_resource:
            repository: alpine
          inputs: [{name: git-repo}]
          outputs: [{name: git-repo}]
          run:
            path: ash
            args:
              - -c
              - |
                set -e
                apk add make python3 py3-yaml
                cd git-repo
                make ci/full-pipeline.yaml

      - set_pipeline: self
        file: git-repo/ci/full-pipeline.yaml

