apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mumble.fullname" . }}
  labels:
    {{- include "mumble.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mumble.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mumble.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mumble.fullname" . }}
                  key: timezone
            - name: SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mumble.fullname" . }}
                  key: superUserPassword
          ports:
            - name: tcp
              containerPort: 64378
              protocol: TCP
            - name: udp
              containerPort: 64378
              protocol: UDP
          volumeMounts:
            - name: config-volume
              mountPath: /etc/mumble
            - name: data-volume
              mountPath: /var/lib/mumble-server
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          mountPath: /etc/mumble
          configMap:
            name: {{ include "mumble.fullname" . }}
            items:
              - key: config
                path: config.ini
            optional: false
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "mumble.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
