apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "mumble.fullname" . }}
  labels:
    {{- include "mumble.labels" . | nindent 4 }}
data:
  superUserPassword: {{ .Values.superUserPassword | b64enc | quote }}
