---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mumble.fullname" . }}
  labels:
    {{- include "mumble.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
    - port: {{ .Values.service.port }}
      targetPort: udp
      protocol: UDP
      name: udp
  selector:
    {{- include "mumble.selectorLabels" . | nindent 4 }}
